export const COUNTRY_CODES: Record<string, string> = {
  美国: "US",
  欧洲: "DE",
  东南亚: "SG",
  日本: "JP",
  中东: "AE",
  澳洲: "AU",
  印度: "IN",
  拉美: "MX",
  全球: "US",
  USA: "US",
  Europe: "DE",
  "Southeast Asia": "SG",
  Japan: "JP",
  "Middle East": "AE",
  Australia: "AU",
  India: "IN",
  "Latin America": "MX",
  Global: "US",
};

export const COUNTRY_SEARCH_TERMS: Record<string, string> = {
  美国: "USA United States",
  欧洲: "Europe Germany UK France",
  东南亚: "Southeast Asia Thailand Vietnam Singapore",
  日本: "Japan",
  中东: "Middle East UAE Dubai",
  澳洲: "Australia",
  印度: "India",
  拉美: "Latin America Mexico Brazil",
  全球: "global worldwide",
};

export const COMPETITOR_DOMAIN_BLACKLIST = [
  "alibaba.com",
  "aliexpress.com",
  "amazon.com",
  "made-in-china.com",
  "globalsources.com",
  "thomasnet.com",
  "indiamart.com",
  "tradeindia.com",
  "ec21.com",
  "tradekey.com",
];

export const GENERIC_DOMAIN_BLACKLIST = [
  "wikipedia.org",
  "linkedin.com",
  "facebook.com",
  "instagram.com",
  "twitter.com",
  "x.com",
  "youtube.com",
  "reddit.com",
  "yelp.com",
  "yellowpages.com",
  "bbb.org",
  "bloomberg.com",
  "reuters.com",
  "forbes.com",
  "businesswire.com",
  "prnewswire.com",
  "cnn.com",
  "bbc.com",
  "techcrunch.com",
  // Email/webmail providers - not buyers
  "yahoo.com",
  "yahoo.co.jp",
  "yahoo.com.tw",
  "yahoo.co.uk",
  "mail.yahoo.com",
  "gmail.com",
  "outlook.com",
  "hotmail.com",
  "mail.com",
  "protonmail.com",
  // Login / auth portals
  "login.com",
  "login.gov",
  "login.microsoftonline.com",
  "accounts.google.com",
  "auth0.com",
  "okta.com",
  // Large tech giants unrelated to product sourcing
  "google.com",
  "microsoft.com",
  "apple.com",
  "amazon.com",
  "meta.com",
  "tiktok.com",
  "shopify.com",
  "ebay.com",
  "walmart.com",
  "target.com",
  // News / media
  "wsj.com",
  "nytimes.com",
  "theguardian.com",
  "wired.com",
  "venturebeat.com",
];

export const GENERIC_EMAILS = [
  "noreply",
  "no-reply",
  "donotreply",
  "postmaster",
  "webmaster",
  "hostmaster",
  "abuse",
  "spam",
  "admin",
  "administrator",
  "support",
  "help",
  "helpdesk",
  "contact",
  "info",
  "information",
  "sales",
  "marketing",
  "hr",
  "careers",
  "jobs",
  "press",
  "media",
  "legal",
  "billing",
  "accounts",
  "accounting",
  "finance",
  "office",
  "hello",
  "team",
  "news",
  "newsletter",
];

export const TARGET_MARKETS = [
  { label: "美国", value: "美国", flag: "🇺🇸" },
  { label: "欧洲", value: "欧洲", flag: "🇪🇺" },
  { label: "东南亚", value: "东南亚", flag: "🌏" },
  { label: "日本", value: "日本", flag: "🇯🇵" },
  { label: "中东", value: "中东", flag: "🌍" },
  { label: "澳洲", value: "澳洲", flag: "🇦🇺" },
  { label: "印度", value: "印度", flag: "🇮🇳" },
  { label: "拉美", value: "拉美", flag: "🌎" },
  { label: "全球", value: "全球", flag: "🌐" },
];
