/**
 * POST /api/email/send
 *
 * V1.0 MVP: 不代发邮件，改为返回 mailto: URL 由用户本地邮箱发送。
 * [REMOVED] Resend 代发逻辑 — V1.0 坚决不做代发，避免 API Key / 域名验证等复杂依赖。
 *
 * 响应:
 *   { mailtoUrl: string, recordId?: string }
 */

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { buyerMatchId, subject, body: emailBody, subjectVariant, userId, toEmail } = body;

    if (!toEmail || !subject || !emailBody) {
      return NextResponse.json(
        { error: "Missing required fields: toEmail, subject, body" },
        { status: 400 }
      );
    }

    // Build mailto: URL — opens user's local email client
    const mailtoUrl =
      `mailto:${encodeURIComponent(toEmail)}` +
      `?subject=${encodeURIComponent(subject)}` +
      `&body=${encodeURIComponent(emailBody)}`;

    // Record the intent in DB (status = "pending_user_send")
    const record = await prisma.emailOutreach.create({
      data: {
        userId: userId || "demo-user",
        buyerMatchId,
        subject,
        subjectVariant: subjectVariant || "A",
        body: emailBody,
        status: "pending_user_send",
        // sentAt: null (nullable, omit so DB default applies)
        // trackingPixelId: auto-generated by DB default (cuid)
      },
    }).catch(() => null);

    return NextResponse.json({
      success: true,
      mailtoUrl,
      recordId: record?.id ?? null,
      note: "V1.0: 请点击 mailtoUrl 在本地邮箱发送",
    });
  } catch (err) {
    console.error("[/api/email/send]", err);
    return NextResponse.json({ error: "Failed to build mailto URL" }, { status: 500 });
  }
}
